### ISSUE TITLE
Last menu item hidden behind attribution footer

### ISSUE THREAD

**Issue by Starfox64** [Redocly/redoc#2190] opened 2022-10-20 15:23 UTC
**Describe the bug**
The `RedocAttribution` component at the bottom of the side menu hides the last menu item.

**Expected behavior**
The last menu item should remain above the `RedocAttribution`.

**Minimal reproducible OpenAPI snippet(if possible)**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/1530720/196990510-ddd41f83-5fe7-41de-a2d7-7bdc14981b5b.png)

**Additional context**
N/A

**Comment by AlexVarchuk** [comment] 2022-10-21 14:31
Hi @Starfox64, thank you for the issue.  Please provide more details for reproducing (screen size, OS, definition, etc.). Also, make sure you are using the last version of Redoc.

**Comment by lspgn** [comment] 2022-10-22 19:16
It's likely this issue https://github.com/Redocly/redoc/pull/2132
Bug was introduced in [v2.0.0-rc.73](https://github.com/Redocly/redoc/releases/tag/v2.0.0-rc.73) and fixed in [v2.0.0-rc.76](https://github.com/Redocly/redoc/releases/tag/v2.0.0-rc.76).

I noticed the problem with Fastapi's redoc endpoint.
The reason is the bundle used ([docs.py](https://github.com/tiangolo/fastapi/blob/90fc4299d1d24a54dda8bf6f01cf3779ce6cf467/fastapi/openapi/docs.py#L79)) is `https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js`.

And when we look at `next` in [jsdelivr](https://www.npmjs.com/package/redoc), it points to `v2.0.0-rc.75`.
![Screenshot of jsdelivr](https://user-images.githubusercontent.com/27725238/197358541-4555ebc1-0e23-4143-8036-77e1b28b9c79.png)

Manually pointing to `rc-76` or `latest` fixes the problem.

**Comment by AlexVarchuk** [comment] 2022-10-25 14:34
> Can I expect next to eventually be bumped to a more recent release or should it be deprecated in favor of latest?

We have the plan to update the `next` to `2.0.0` and deprecate it after.

**Closed** 2022-11-19 11:12 UTC
Labels: Type: Bug, help wanted
