### ISSUE TITLE
False recursion detected with oneOf and nested objects inside array

### ISSUE THREAD

**Issue by simon-spinner** [Redocly/redoc#2066] opened 2022-06-28 15:10 UTC
**Describe the bug**
The redoc output prints out the complete structure of the object for the first oneOf case, but only shows recursive for the object inside the array of the second oneOf case. Both oneOf cases have basically the same structure.

**Expected behavior**
Both cases of the oneOf are rendered with the complete object structure. No recursion should be detected.

The recursion goes away if I either remove:

- `$ref: '#/components/schemas/Mixin'` from ItemA and ItemB, or
- `$ref: '#/components/schemas/BaseItem'` from BaseItemA and BaseItemB

**Minimal reproducible OpenAPI snippet(if possible)**

```yaml
openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/OneOfModel'
components:
  schemas:
    OneOfModel:
      type: object
      oneOf:
        - $ref: '#/components/schemas/TypeAModel'
        - $ref: '#/components/schemas/TypeBModel'
    BaseModel:
      type: object
      properties:
        type:
          type: string
          enum:
            - a
            - b
    TypeAModel:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseModel'
      properties:
        array:
          type: array
          items:
            $ref: '#/components/schemas/ItemA'
    TypeBModel:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseModel'
      properties:
        array:
          type: array
          items:
            $ref: '#/components/schemas/ItemB'
    ItemA:
      type: object
      allOf:
        - $ref: '#/components/schemas/Mixin'
        - $ref: '#/components/schemas/BaseItemA'
    BaseItemA:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        a:
          type: integer    
    ItemB:
      type: object
      allOf:
        - $ref: '#/components/schemas/Mixin'
        - $ref: '#/components/schemas/BaseItemB'
    BaseItemB:
      type: object
      allOf:
        - $ref: '#/components/schemas/BaseItem'
      properties:
        b:
          type: string
    Mixin:
      type: object
      properties:
        name:
          type: string
    BaseItem:
      type: object
      properties:
        id:
          type: string        
```

**Screenshots**
OneOf case 1
![image](https://user-images.githubusercontent.com/22886661/176214208-ca7bf905-7216-4083-b9fb-035d3b5d91ff.png)

OneOf case 2
![image](https://user-images.githubusercontent.com/22886661/176214283-c96af61c-3040-4ccc-bab0-a2eeac680989.png)

**Additional context**
redoc version 2.0.0-rc.72

**Comment by RomanHotsiy** [comment] 2022-06-28 17:05
This is a duplicate of https://github.com/Redocly/redoc/issues/1154

And there is a good news: this is going to be fixed this week. I finally have a working fix and tested it good enough to be ready to publish it.

_(I just tested your example on the new code and it works fine)_

So stay tuned 🙌

**Closed by RomanHotsiy** 2022-06-28 17:05 UTC
