### ISSUE TITLE
YAML support for SpecURL broke with v2.0.0-rc.51

### ISSUE THREAD

**Issue by tfranzel** [Redocly/redoc#1574] opened 2021-04-09 12:08 UTC
Hi!

rc51 introduced a regression where YAML spec are not accepted anymore. rc50 works fine with a YAML URL. URL with a JSON target always works.

```html
<redoc spec-url="{{ schema_url }}"></redoc>
```

Error message: `Document must be JSON object, got string`

screenshots at: https://github.com/tfranzel/drf-spectacular/issues/363

looks like this issue originated somewhere around here: https://github.com/Redocly/redoc/compare/8bee3d5..60bf22e#diff-da06c79d8076556aba9bc86abc13358ead85f9aadc2d54c8e4de75c1f7bde9a7R24

**Comment by RomanHotsiy** [comment] 2021-04-09 12:23
Duplicate of https://github.com/Redocly/redoc/issues/1573

We're working on it!

**Closed by RomanHotsiy** 2021-04-09 12:23 UTC

**Comment by tfranzel** [comment] 2021-04-09 17:59
awesome, thanks! sry for the duplicate but i didn't see the other temporarily closed issue.
