### ISSUE TITLE
Markdown  code block description issue

### ISSUE THREAD

**Issue by yannan** [Redocly/redoc#1141] opened 2019-12-13 09:15 UTC
I want to creating a code block using markdown in the description field.
Everything is working fine util I use python comment character "#".

Example:

```
openapi: 3.0.2
info:
    title: test
    version: 1.0
    description: |
      # python example
      ```python
      # -*- coding: UTF-8 -*-
      import hmac
      import hashlib
      import json
      ```
```
The result of render is:
![TIM图片20191213165950](https://user-images.githubusercontent.com/7194092/70787603-fee0d180-1dc9-11ea-8865-3cc06281959a.png)
the block is empty...

As the result of render in editor.swagger.io is:
![TIM图片20191213165705](https://user-images.githubusercontent.com/7194092/70787613-056f4900-1dca-11ea-8d03-9cac4babe093.png)

I think the "#" character in code block may be handled as a heading.

**Comment by RomanHotsiy** [comment] 2019-12-13 09:16
Duplicate of https://github.com/Redocly/redoc/issues/1116

Will be fixed in the new release (coming today)

**Closed by RomanHotsiy** 2019-12-13 09:16 UTC
