### ISSUE TITLE
Display descriptions for oneOf selectors

### ISSUE THREAD

**Issue by eu42** [Redocly/redoc#927] opened 2019-05-29 00:52 UTC
Although options for `oneOf` displayed very nicely, their descriptions are ignored by ReDoc. It'd be great if the descriptions are also displayed.

Sample spec:
```
openapi: 3.0.2
info:
  title: API
  version: 1.0.0
paths:
  /endpoint1:
    get:
      responses:
        '200':
          description: Completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response_schema'
      operationId: endpoint1
components:
  schemas:
    schema1:
      title: schema1
      required:
      - y
      type: object
      properties:
        y:
          title: y
          maximum: 100.0
          minimum: 0.0
          type: integer
      description: "schema1 description"
    schema2:
      title: schema2
      required:
      - x
      type: object
      properties:
        x:
          title: x
          maximum: 100.0
          minimum: 0.0
          type: integer
      description: "schema2 description"
    response_schema:
      required:
      - field1
      type: object
      properties:
        field1:
          anyOf:
          - $ref: '#/components/schemas/schema1'
          - $ref: '#/components/schemas/schema2'
          description: "field1 description"
      description: "response schema description"
```

Output:
<img width="800" alt="Screen Shot 2019-05-29 at 02 39 11" src="https://user-images.githubusercontent.com/15113365/58521137-b5c58900-81bb-11e9-9566-35935dbef224.png">

As one can see, the description for schema1 is missing in the screenshot.

The description can be added above schema properties, something like this:
<img width="803" alt="Screen Shot 2019-05-29 at 02 50 12" src="https://user-images.githubusercontent.com/15113365/58521318-9713c200-81bc-11e9-9d13-ebbc561a510a.png">

**Comment by v-kolesnikov** [comment] 2019-06-25 15:29
I've met the same problem.

**Comment by malpiatko** [comment] 2020-06-24 20:13
I don't think it's a duplicate of #932. I'd also love to see this feature or a tip how to achieve this

**Comment by RomanHotsiy** [comment] 2020-06-27 15:06
Dup of https://github.com/Redocly/redoc/issues/752

**Closed by RomanHotsiy** 2020-06-27 15:06 UTC
