### ISSUE TITLE
Path parameter examples not shown

### ISSUE THREAD

**Issue by m-mohr** [Redocly/redoc#971] opened 2019-07-10 13:25 UTC
I have a path paremeter defined as follows:

```
...
    "parameters": {
      "file_path": {
        "name": "path",
        "in": "path",
        "description": "Path of the file, relative to the user's root directory.\r\n\r\n**Note:** Folder and file names in the path MUST be url-encoded. The path separator `/` and the file extension separator `.` MUST NOT be url-encoded. This may be shown incorrectly in rendered versions due to [OpenAPI 3 not supporting path parameters which contain slashes](https://github.com/OAI/OpenAPI-Specification/issues/892).",
        "required": true,
        "schema": {
          "type": "string"
        },
        "examples": {
          "normal": {
            "description": "A path without special chars. It describes a file `europe.geojson` in a folder called `borders`.",
            "value": "borders/europe.geojson"
          },
          "specialchars": {
            "description": "A path with special chars. It describes a file `münster.shp` in folders called `europe` and `österreich`.",
            "value": "europe/%C3%B6sterreich/m%C3%BCnster.shp"
          }
        }
      }
    }
...
```

Unfortunately, the examples are not shown:

![image](https://user-images.githubusercontent.com/8262166/60972575-d3dbe880-a326-11e9-859a-c653945d7c00.png)

I'd expect them to show up where the red arrow is for example. If you specify a single example in a schema, it is shown (see `john_doe` for the user_id).

**Comment by RomanHotsiy** [comment] 2019-07-11 05:03
This is a missing feature. PRs are welcome

**Comment by RomanHotsiy** [comment] 2019-07-11 08:49
Actually, it's a duplicate of #858

**Closed by RomanHotsiy** 2019-07-11 08:49 UTC
Labels: enhancement, help wanted

**Comment by m-mohr** [comment] 2019-07-11 08:56
Indeed, sorry for the duplicate.
