### ISSUE TITLE
Custom requests examples

### ISSUE THREAD

**Issue by hawy31** [Redocly/redoc#1039] opened 2019-09-16 13:27 UTC
Hi! I need to make custom request examples, like a curl or something. How I can did it?

For example: 
**Actually**
http://api.somedomain.com/users

**What I need**
curl -i -X GET https://api.somedomain.com/users
-H "Authorization: Example Token"

Someone help, thank u

**Comment by adamaltman** [comment] 2019-09-22 16:10
Look over here: https://redocly.github.io/redoc/#tag/pet

![image](https://user-images.githubusercontent.com/1161871/65390991-4dca1e00-dd29-11e9-9333-298bb4d111cc.png)

Find the corresponding example:

https://github.com/Redocly/redoc/blob/master/demo/openapi.yaml#L109

Adjust the `lang` to `curl` and change the example.

**Comment by hawy31** [comment] 2019-09-23 03:09
I want automatically generate from payload :) can I extended basic functionality?

**Comment by adamaltman** [comment] 2019-09-23 03:13
Like here: #15 ?

**Comment by hawy31** [comment] 2019-09-23 03:14
yes

**Comment by adamaltman** [comment] 2019-09-23 03:17
Closing as a duplicate of #15 then.

**Closed by adamaltman** 2019-09-23 03:17 UTC
Labels: duplicate
