### ISSUE TITLE
Is there a limit on the level of the schema/json of the Request Body to be displayed in "Try it" Console in Redocly ? <Works with Swagger UI>

### ISSUE THREAD

**Issue by manjunath-batakurki** [Redocly/redoc#1694] opened 2021-07-15 15:15 UTC
Describe the bug
We are seeing that the the redocly schema shows the full schema in the request schema, but the "Try it" Console trunncates it to after a particular level. Is this expected ? how to fix it ?
There is schema to be displayed after "Default", but it is getting truncated and displayed as `"Default": {}`
![image](https://user-images.githubusercontent.com/78580773/125812134-bed2fbd2-5466-4224-a450-469ee7a8957f.png)

But the Request schema shows the same(After `Default`)
![image](https://user-images.githubusercontent.com/78580773/125812360-e0a0416b-6a66-4faa-8a33-a199fe7b3e83.png)

**attaching the JSON for Reference**
[json_issue.zip](https://github.com/Redocly/redoc/files/6824234/json_issue.zip)

We try the same using Swagger UI. We are able to see this working in Swagger UI.

![image](https://user-images.githubusercontent.com/78580773/125829163-98446b8b-93a7-44f5-8488-9cb402de0b90.png)

**For your info, we are using redocly 1.0.0-beta.159**

**Please Note that this is blocking us from invoking and using `Try it` Console.**

**Comment by bhatpriyanka8** [comment] 2021-07-15 17:55
To add to this, 
GET calls responses which are equally huge get rendered pretty well. Looks like the issue is with Request body in POST/PUT. Looking forward to a fix for this soon!

**Comment by manjunath-batakurki** [comment] 2021-07-15 18:02
**Same issue is seen with Sample Response Body also.**

![image](https://user-images.githubusercontent.com/78580773/125835770-fdcf4d32-e554-455c-992b-2b9b3c549636.png)

**Comment by RomanHotsiy** [comment] 2021-07-16 06:41
There is no Try it out in the open-source version. Issues about reference docs product should be reported to team@redocly.com

**Closed by RomanHotsiy** 2021-07-16 06:41 UTC
