### ISSUE TITLE
Redoc source map error loading from local server

### ISSUE THREAD

**Issue by phr34k** [Redocly/redoc#1217] opened 2020-03-27 16:28 UTC
I'm using redoc together with django rest framework + drf_yasg to generate api documentation. When I follow the tutorials with the html in the TL;DR section of redocs documentation it always gives me a layout with two columns.

With redoc-cli I was able to get better results and especially with the bundle option I'm able to get pre-generated HTML and loading it in Firefox everything looks correct. However, once served in my local development server; that same HTML somehow now loads in firefox as two-column redoc webpage. 

Loading it in Chrome gives a three column page. When I look at Firefox's debug console, I see some weird "Source map error: Error: NetworkError when attempting to fetch resource." Any idea what's going on over there?

**Comment by RomanHotsiy** [comment] 2020-03-27 16:31
Source map error has nothing to do with this error.

Could you attach screenshots of your issue?

**Comment by phr34k** [comment] 2020-03-27 17:52
@RomanHotsiy two screenshots one taken from Chrome and one taken in Firefox. Chrome is what I expect Firefox is different for some reason. Notice the side menu is gone for some reason under firefox.

![chrome](https://user-images.githubusercontent.com/1190003/77784781-6100d200-705b-11ea-8613-0357da90b424.PNG)

![firefox](https://user-images.githubusercontent.com/1190003/77784779-60683b80-705b-11ea-9906-c6bf9a5af043.PNG)

Interestingly enough if I make firefox load the generated HTML file from disk it does work like expected. 

![firefox_local_file](https://user-images.githubusercontent.com/1190003/77785026-d4a2df00-705b-11ea-84e5-81a2b3df129e.PNG)

**Comment by RomanHotsiy** [comment] 2020-05-09 12:19
Oh, this is very strange. Could you inspect the source of the page in the second screenshot and send it over here?

**Comment by phr34k** [comment] 2020-05-11 11:38
I'm afraid not I don't have the code at hand anymore- but this happened for me I believe because of stylesheets. I tried fiddling around with it some more with the web debugger and mostly used the responsible designer to resize the window viewport.

The result was at some cases I was able to get all three layouts side by side, and in some it was under each other stacked. Which makes sense since redoc does that automatically; likely it may be a margin or a padding-box that doesn't get calculated appropriately. Maybe it's like a utf-8 bom that messes it up.

**Comment by RomanHotsiy** [comment] 2020-05-11 11:45
Thanks for the update. Closing this. Feel free to reopen if you hit it ever again.

**Closed by RomanHotsiy** 2020-05-11 11:45 UTC

**Comment by phr34k** [comment] 2020-05-11 11:50
I didn't say the problem doesn't exist anymore. I said I don't have the files at hand anymore since it took 2 months to follow up on a discussion. Before you close the issue, please verify if the stylesheets need some fixing.

**Comment by RomanHotsiy** [comment] 2020-05-11 12:05
I can't reproduce it on my side.
If you can't help me to reproduce it I have no choice but to close it for now. If the issue still exists someone will complain in the future, maybe with more specific reproduction instructions.

If you find a way to reproduce it, post it here, please and I will reopen the issue.

Thanks
