### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by vaasav-kumar** [Redocly/redoc#1193] opened 2020-03-02 07:16 UTC
```
{
    description: [Settings](https://domain/settings)
}
```

It opens link in same tab. Also provide some option to open link in new tab.

**Comment by lornajane** [comment] 2023-07-26 15:13
Duplicate of #891 where it was suggested to use an HTML link tag to achieve this. Markdown doesn't have a way to open links in new tabs.

**Closed by lornajane** 2023-07-26 15:13 UTC
Labels: Type: Enhancement, help wanted, feature
