### ISSUE TITLE
Render model definitions? (feature support)

### ISSUE THREAD

**Issue by PedroMD** [Redocly/redoc#134] opened 2016-11-03 18:34 UTC
Hello all,

Thanks for this amazing project! ;) It is now our default view engine of our Swagger spec. 

As you can see in swagger-ui repo, there is [a popular issue](https://github.com/swagger-api/swagger-ui/issues/1052#issuecomment-258185202) where people are asking for Models rendering, just like swagger-editor does. This would be great if it could be added to ReDoc! ;)

Thanks!

**Comment by avkonst** [comment] 2017-05-22 03:55
I am generating a table reference with a list of models in markdown format. It seems it works. Rows in a table are hyperlinks to operations.

**Comment by suds123** [comment] 2017-05-23 08:51
Hi @RomanGotsiy, 

Any thoughts on when this enhancement might be introduced? 

Twitter APIs have something similar "object definition" - https://dev.twitter.com/overview/api/tweets

Thanks!

**Comment by RomanGotsiy** [comment] 2017-05-25 11:22
I don't have this on the roadmap yet.
The next items are "Try it out" feature (which I have already started working on), OpenAPI 3 support + simplified branding/styling. So this feature would take some time to implement.

Although, It is not clear how to do it. OpenAPI is a bit complex.
Would be awesome if you can describe your use cases and describe how you want ReDoc to represent it.
It would help me a lot!

Thanks in advance

**Comment by suds123** [comment] 2017-05-30 12:41
Swagger Editor style model rendering could be good.

![image](https://cloud.githubusercontent.com/assets/8452669/26583550/9fb3a096-453d-11e7-954f-3620ce5acec8.png)

**Comment by K-Leon** [comment] 2017-06-01 21:40
@avkonst Is there any chance to open source this script? I'm looking for a simple way to add the Models.

**Comment by avkonst** [comment] 2017-06-01 22:32
@K-Leon swagger spec is the derived spec in my system. The original definition of the objects, properties and relationships of the model is in the private / internal format. This original definition format is used to generate swagger spec and necessary markdown pages. Since the format and infrastructure for managing it are deeply embedded in the private source code, so I am not able to publish anything helpful. Sorry about this.

**Comment by suds123** [comment] 2017-09-29 15:04
@RomanGotsiy - Found another example of schema/model definition -

https://github.com/sourcey/spectacle

![image](https://user-images.githubusercontent.com/8452669/31022138-d19a4c5c-a52f-11e7-831a-d5bd382c7566.png)

**Comment by Rikhart** [comment] 2018-05-23 21:58
+1 for this issue, I'll like this feature help me so muche, hope will be available soon

**Comment by royrico** [comment] 2018-06-12 19:07
+1 for this issue as well!

**Comment by yvespareteum** [comment] 2018-08-02 09:39
Models rendering is really important for us, as our APIs are based on them !
Can't wait to see that improvement delivered !!!
+1

**Comment by cmeeren** [comment] 2018-08-09 07:58
Just want to add that the ability to render models would improve the feasibility of OpenAPI + ReDoc for documenting hypermedia APIs (where the focus is on resources and their links, not on static paths). One could create a tag for each resource, document the resource in the tag description with a rendering of the model, and then list operations on that resource as normal paths with that tag.

**Comment by bangonkali** [comment] 2018-11-06 12:17
Is there any plan for this?

**Comment by Aykelith** [comment] 2018-11-13 14:07
+1

**Comment by nanov** [comment] 2018-11-14 02:21
I did some work on the matter in [this PR](https://github.com/Rebilly/ReDoc/pull/681).
My solution was to add a new markdown "extension" <object-description> which leaves you the freedom to place those definitions wherever you think they are suitable.

Together with side Tag side menus, the given examples should be easy to achieve.

**Comment by tomq42** [comment] 2019-02-01 08:05
+1 for this.
I'd like to render (selected) model definitions in the menu like operations.
Naively I'd hoped I could put a tag on the schema and it would be rendered under the tag like an operation. I can therefore create my own tag just for certain selected models.

**Comment by shaigluskin** [comment] 2019-03-12 20:16
+1 this is key for us. Swagger UI implementation ugly, but it's there. Redoc is better with without display of model definitions we wont' be able to use it.

**Comment by jmini** [comment] 2019-08-26 14:26
Given some spec that manages 2 entities (Task and Person): [todoApp.yaml](https://github.com/jmini/openapi-experiments/blob/master/OpenAPI-specs/todoApp.yaml) ([ReDoc live demo](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/jmini/openapi-experiments/master/OpenAPI-specs/todoApp.yaml))

My goal is to obtain a list of all models in a similar way than with Swagger-UI or Spectacle (as discussed in this issue).

If I understood it well, the approach proposed by @nanov is to add fake tags for each model and to group them under a single group called “Models” (using `x-tagGroups`). Each of the fake tag is calling the markdown "extension” `SchemaDefinition`

Diff:

```diff
--- a/OpenAPI-specs/todoApp.yaml
+++ b/OpenAPI-specs/todoApp.yaml (adding the necessary metadata)
@@ -13,6 +13,25 @@
   description: All task related operations
 - name: person
   description: All person related operations
+- name: task_model
+  x-displayName: Task
+  description: <SchemaDefinition schemaRef="#/components/schemas/Task" />
+- name: person_model
+  x-displayName: Person
+  description: <SchemaDefinition schemaRef="#/components/schemas/Person" />
+- name: error_model
+  x-displayName: Error
+  description: <SchemaDefinition schemaRef="#/components/schemas/Error" />
+x-tagGroups:
+  - name: Operations
+    tags:
+      - task
+      - person
+  - name: Models
+    tags:
+      - task_model
+      - person_model
+      - error_model
 paths:
   /task:
     get:
```

Result: [todoAppSchemaDef.yaml](https://github.com/jmini/openapi-experiments/blob/master/OpenAPI-specs/todoAppSchemaDef.yaml) ([ReDoc live demo](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/jmini/openapi-experiments/master/OpenAPI-specs/todoAppSchemaDef.yaml))

Maybe I missed something?

---

In my opinion, if the requirement is to display a list of all models, it would be better to just have an Global Option that does this “(e.g. list all models”), without having to add unnecessary metadata to the file.

* With a real spec the number of fake-tags might be big (our spec has about 140 Schema under `components/schema`)
* The additional tags might be misinterpreted by other tools.
* The resulting deep link is `<server>#tag/person_model`, I would prefer `<server>#schema/Person`

---

What are the thoughts?

**Comment by nanov** [comment] 2019-08-27 05:51
You can do it with one tag, models, and then with markdown titles ( ## ) list all your models there.

**Comment by jmini** [comment] 2019-08-27 06:43
@nanov: Thank you a lot for this valuable feedback.

I now have patched my original file like this:

```diff
--- a/OpenAPI-specs/todoApp.yaml
+++ b/OpenAPI-specs/todoApp.yaml
@@ -13,6 +13,25 @@
   description: All task related operations
 - name: person
   description: All person related operations
+- name: models
+  x-displayName: All Models
+  description: |
+    ## Task
+    <SchemaDefinition schemaRef="#/components/schemas/Task" />
+    
+    ## Person
+    <SchemaDefinition schemaRef="#/components/schemas/Person" />
+    
+    ## Error
+    <SchemaDefinition schemaRef="#/components/schemas/Error" />
 paths:
   /task:
     get:
@@ -283,4 +302,4 @@
         message:
           description: Short description of the error
           type: string
          example: Could not perform the task
```

Result: [todoAppSchemaDef2.yaml](https://github.com/jmini/openapi-experiments/blob/master/OpenAPI-specs/todoAppSchemaDef2.yaml) ([ReDoc live demo](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/jmini/openapi-experiments/master/OpenAPI-specs/todoAppSchemaDef2.yaml))

---
Which is already better:

* only one fake tag (with a really big description)
* The resulting deep link is `<server>#section/Person`, I would prefer `<server>#schema/Person` (but at least this is not `#tag/…

Screenshot:
<img width="965" alt="Screenshot" src="https://user-images.githubusercontent.com/1222165/63747005-610ed880-c8a6-11e9-98f2-cdfce4199df1.png">

---

My preferred solution would be to not have to write this `models` tag, but this needs a change in ReDoc.

**Comment by nanov** [comment] 2019-08-27 07:22
It's not about a change in ReDoc, it is about giving you the freedom to choose which models in what oder are displayed and optionally giving them description, also this models could be mixed with the endpoints menus, the same way stripe does it.

**Comment by jmini** [comment] 2019-08-27 08:19
@nanov: I understand the feature, it is just that I am more looking for an exhaustive list approach
where some HTML documentation is created for all schemas under `components/schemas` out-of the box (without having to write additional content to the spec that is only ReDoc specific and not stored into an extension). The element in the generated pages should be deep-linkable.

With your suggested approach, we I think we can make it work for us. But we are now speaking of creating one generic OpenAPI spec (the one we have today) and one ReDoc-specific version with the additional items required for the display we would like to get.

---

IMO it really depends how you are using authoring and using the OpenAPI spec. We are generating it, driven by our back-end. I expect the generated HTML-pages to be similar to Javadoc/tsdoc => provide an exhaustive list of the OpenAPI content (in an human readable way).

If you are closer to documentation (your OpenAPI spec is telling you a story), you might want to select the more prominent schemas and maybe add text in between.

**Comment by nanov** [comment] 2019-08-27 08:48
> With your suggested approach, we I think we can make it work for us. But we are now speaking of creating one generic OpenAPI spec (the one we have today) and one ReDoc-specific version with the additional items required for the display we would like to get.

This is not the worst approach, i think stripe does something similar.

> without having to write additional content to the spec that is only ReDoc specific and not stored into an extension

I agree agree with your point, however I am not the developer behind ReDoc, and that was the way i decided in order to do as less changes as possible to the original software and make it work. I am open to suggestions which would give the functionality you are tabling about ( probably some kind of extension, ```x-richDescrption``` is one way to go but the tag stays, or maybe ```x-redocTags``` that can be used  inside tag groups.  ). Do you have something in mind that would also make the authoring/generation of the spec  straight-forward?

> IMO it really depends how you are using authoring and using the OpenAPI spec. We are generating it, driven by our back-end. I expect the generated HTML-pages to be similar to Javadoc/tsdoc => provide an exhaustive list of the OpenAPI content (in an human readable way).
>
> If you are closer to documentation (your OpenAPI spec is telling you a story), you might want to select the more prominent schemas and maybe add text in between.

I totally agree.

**Comment by jmini** [comment] 2019-08-27 09:44
> I agree agree with your point, however I am not the developer behind ReDoc, and that was the way i decided in order to do as less changes as possible to the original software and make it work. 

Understood and your feature is great!

> probably some kind of extension, `x-richDescription` is one way to go but the tag stays, or maybe `x-redocTags` that can be used inside tag groups.

+1

I would prefer something solved with an extension. IMO with OpenAPI it is quite frequent that the Spec is enhanced with extensions, that only few tools will understand. This is something that already exists with `x-logo`.

With the current approach, the additional unused tag (not an extension) is a no-go when you browse the spec with other tools. Here a screenshot of my `todoAppSchemaDef2.yaml` spec with Swagger-UI ([live-demo](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jmini/openapi-experiments/master/OpenAPI-specs/todoAppSchemaDef2.yaml#/)):

<img width="549" alt="Screenshot with Swagger-UI" src="https://user-images.githubusercontent.com/1222165/63760295-5876cc00-c8bf-11e9-9658-f1096bf42e5d.png">

---

We plan to create 2 pages (one for all Schemas, and one for Callbacks -- see #411), so probably `x-redocTags` next to `tags` is the best solution.

**Comment by nanov** [comment] 2019-08-27 11:44
@RomanHotsiy are you open to discuss this on an api/architecture level?

**Comment by RomanHotsiy** [comment] 2019-08-27 13:00
I understand the use case and the problem for people who autogenerate their docs...

I don't quite like the idea of displaying all the schemas similar to how SwaggerUI does it. There may be lots of internal/utility schemas that do not make any sense to display under a separate menu item.

I'm not sure yet on how to solve the use case but right now I like the @tomq42 	idea:

>  I could put a tag on the schema and it would be rendered under the tag like an operation. I can therefore create my own tag just for certain selected models.

What do you think about this idea?

**Comment by nanov** [comment] 2019-08-27 13:34
> I don't quite like the idea of displaying all the schemas similar to how SwaggerUI does it. There may be lots of internal/utility schemas that do not make any sense to display under a separate menu item.

I totally agree, that's why as explained I chose the implantation i did.

>> I could put a tag on the schema and it would be rendered under the tag like an operation. I can therefore create my own tag just for certain selected models.

> What do you think about this idea?

I am not exactly sure how this could be implemented AFAIK schemas do not accept tag property ( x-tag could be an option ), and then you loose the ability to add text and control where exactly those schemas will be displayed. Maybe I am understanding it wrong?

**Comment by jmini** [comment] 2019-08-27 15:21
> There may be lots of internal/utility schemas that do not make any sense to display under a separate menu item.

We had the exact same discussion.

We have main models for sure, but sometime in a text-documentation (how-to, faq, architecture description) you would like to deep link to one of those secondary model. This is why we believe that we need the exhaustive list.

---

In my opinion, if ReDoc was implementing the "list-all-models-automatically" feature, this should be an option `nativeScrollbars` or `theme`. It can be `false` by default.

---

Because we are generating our spec, the current implementation with the Markdown Extension is OK, we can generate the all model page we need (containing a `<SchemaDefinition>` extension call for each model).

The only thing that we would like to get improved is the place of this page. Having to create an unused-tag is really strange. We plan to distribute our spec and we would like that it looks also good with other viewer.

Solving this with `x-redocTags` instead of `tags` would work for us.

**Comment by adamaltman** [comment] 2019-09-22 18:11
Models are displayed inline in the Redoc documentation.  So you don't need to click around.  You can expand any request or response and see the model definition right there.

> There may be lots of internal/utility schemas that do not make any sense to display under a separate menu item.

This is a real problem for us at Rebilly -- we have hundreds of schemas.  If you look at the two most revered docs, Stripe and Twilio, they only display "resource" level objects.  And they are always done in the context of the "tag" (set of closely related operations around that resource).  On the other hand, these docs don't explain responses and instead mention they "return the resource", or show an example only.  In the case of returning a paginator/collection, they each follow their own object style and it's defined elsewhere.

**Comment by achuprin** [comment] 2020-02-14 09:56
Hi. Is there any way to show schema definition for concrete model of polymorphic type?
Imagine i have the following definition of polymorphic model:
```yaml
Update:
  discriminator:
    propertyName: update_type
    mapping:
      update1: '#/components/schemas/Update1'
      update2: '#/components/schemas/Update2'
  properties:
    update_type:
      type: string
  required:
    - update_type
Update1:
  allOf:
    - $ref: '#/components/schemas/Update'
    - properties:
        message:
          allOf:
            - $ref: '#/components/schemas/Message'
      required:
        - message
Update2:
  allOf:
    - $ref: '#/components/schemas/Update'
    - properties:
        user:
          allOf:
            - $ref: '#/components/schemas/User'
      required:
        - user
```

In the sidebar i want to refer to `Update2` schema:
```yaml
  - name: update_model
    x-displayName: Update2
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/Update2"/>
```

But it renders the full `Update` schema where user should choose `update_type` in select bot to see `Update2` definition.

Is it expected behaviour or am i missing something?

**Comment by chandansahaiem** [comment] 2021-03-11 12:15
> Swagger Editor style model rendering could be good.
> ReDoc Navigation could be that Models tag appear on the left pane with all models link listed under it and by clicking on a model name, the middle pane displays the model.
> 
> ![image](https://cloud.githubusercontent.com/assets/8452669/26583550/9fb3a096-453d-11e7-954f-3620ce5acec8.png)

**Comment by amcgaw07** [comment] 2021-03-11 18:47
Is there a way to get redoc to render model definitions under the old OpenAPI 2.0 specifications of '#/definitions/User'?

Every example here seems to be using 3.0 with their schemas under '#/components/schema/User', but mine is refusing the render a definitions path within a tag definition such as 

` ` ` 
- name: models
   x-displayName: All Models
   definition: |
       ## USER
       <SchemaDefinition schemaRef="#/definitions/User" />

` ` `

**Comment by TBBle** [comment] 2021-03-16 23:20
I'd be happy to just have the models that I've defined in /components/schemas be rendered (by some flag in the `<redoc>` tag, I guess), or perhaps just ones that aren't currently referenced elsewhere.

My specific use-case is using OpenAPI to define on-disk file formats: there's no paths in our spec, and ReDoc is just coming up with nothing but the spec header for this case. I'd hoped to see the list of defined models, like Swagger UI provides, but would also accept just the unreferenced models, since those are the "top-level" entry points for our API.

**Comment by AlexVarchuk** [comment] 2022-05-16 08:46
We already support the rendering model. Regarding that, we close this issue. Feel free to open new issues with enhancements or bugs 🙈

**Closed by AlexVarchuk** 2022-05-16 08:46 UTC
Labels: Type: Enhancement, feature
