### ISSUE TITLE
redoc-cli: sidebar and page scrolling issues

### ISSUE THREAD

**Issue by IBrokeYourCode** [Redocly/redoc#1168] opened 2020-02-06 12:25 UTC
I am using redoc-cli 0.9.5 on MacOS Catalina.

In addition to [this issue](https://github.com/Redocly/redoc/issues/1167), I've been having another problem since updating Chrome somewhere in the last 24 hours. 

1. In the sidebar, when clicked once, the item does not expand. Clicking twice takes me to the that tag.
2. The page always returns back to top after scrolling a bit up or down. Interestingly, when that happens, for a split second I can see the last clicked tag expanded before it collapses again.

One exception is that when using `serve` instead of `bundle`, the sidebar expanding seems to work until I click the same tag twice in a row (so expand and then collapse it) or if I scroll down far enough for the sidebar to disappear from view.

I did not observe any of the above in Firefox (72.0.2) or Safari (15608.5.11)

**Comment by yurasmetanka** [comment] 2020-02-06 12:32
Same issue on Fedora, Chrome 80.0.3987.87, on previous Chrome versions everything works fine

**Comment by IBrokeYourCode** [comment] 2020-02-06 12:40
It may also be worth mentioning that I've opened redoc-cli static bundle files that I generated back in November, with redoc-cli 0.8.6/redoc20.0.0-rc13, and the behavior is the same.

**Comment by alecwcp** [comment] 2020-02-08 15:20
Same issue on Linux (Ubuntu 18.04) with Chrome 80.0.3987.87-1. Previous installed Chrome version was 79.0.3945.130-1, didn't have this issue.

**Comment by RomanHotsiy** [comment] 2020-02-09 13:59
I've been traveling for the last week so sorry for the delay. I'm on it now.

**Comment by RomanHotsiy** [comment] 2020-02-09 14:20
Should be fixed on redoc-cli@0.9.6 and (redoc@v2.0.0-rc.23).

Could anyone please verify it so I can close this issue?

**Comment by IBrokeYourCode** [comment] 2020-02-09 17:41
@RomanHotsiy  I'll let you know tomorrow when I'm back at work.

**Comment by alecwcp** [comment] 2020-02-09 18:07
@RomanHotsiy Thanks, this is resolved when using `<script src="https://cdn.jsdelivr.net/npm/redoc@v2.0.0-rc.23/bundles/redoc.standalone.js"> </script>`. When will this be available at `<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>`?

**Comment by IBrokeYourCode** [comment] 2020-02-10 07:10
@RomanHotsiy `serve` seems to be working OK, but `bundle` is completely mixed up (and still has the problem that if I scroll too far, it returns to the top of the page):
![image](https://user-images.githubusercontent.com/23450220/74128151-d106e600-4bdc-11ea-8949-785f299c56e7.png)

**Comment by RomanHotsiy** [comment] 2020-02-10 10:41
@IBrokeYourCode, your mixed up bundle looks unrelated to the original issue. Are you able to consistently reproduce this broken bundle?

**Comment by IBrokeYourCode** [comment] 2020-02-10 10:49
@RomanHotsiy 
Yes, I tried it on a few different specs, including petstore.yaml from the Swagger website. The effect is the same every time.
After reverting to redoc-cli 0.9.5, the mix-up does not occur.

**Comment by RomanHotsiy** [comment] 2020-02-10 11:10
Well, I can't reproduce it.

```
npx redoc-cli@0.9.6 bundle https://redocly.github.io/redoc/openapi.yaml
```

Produces correct page.

Could you share your exact command/options used?

**Comment by IBrokeYourCode** [comment] 2020-02-10 11:21
When I tried npx as in your example, the bundle is correct. I used yarn to install redoc-cli globally on my system, maybe something's wrong here.

Sorry for the false alarm.

**Comment by jpinkster** [comment] 2020-02-14 13:29
Confirming that upgrading to 0.9.6 fixes the chrome issue

**Comment by RomanHotsiy** [comment] 2020-02-14 13:31
Thanks!

**Closed by RomanHotsiy** 2020-02-14 13:31 UTC

**Comment by ricky-at-domain** [comment] 2020-07-23 12:09
the issue still exists when I insert it into WordPress custom HTML widget
`<script src="https://cdn.jsdelivr.net/npm/redoc@v2.0.0-rc.23/bundles/redoc.standalone.js"> </script>`
