### ISSUE TITLE
Is there an option to remove excessive whitespace?

### ISSUE THREAD

**Issue by securisec** [Redocly/redoc#874] opened 2019-03-27 14:51 UTC
I am writing some simple api documentation using openapi 3.0.0, but am running into an issue with excessive whitespaces in my headings and sections. See attached screenshot.

I am following the example for the [docker engine api docs]() which does not seem to have any excess whitespace. Is there is a setting that can reduce such excessive whitespaces?

I am building a static file using `redoc-cli bundle swagger.yaml --output ./static/docs.html --options.hideDownloadButton --options.noAutoAuth`. My yaml is:
```
    description: |

    # Definations
    ## Entry
      some data
    ## Section
      other data
    ## Collection
      some collection
```

![image](https://user-images.githubusercontent.com/22226823/55085851-b160ef00-50ea-11e9-8b94-79240f184ebb.png)

**Comment by RomanGotsiy** [comment] 2019-03-27 16:46
It has been fixed in https://github.com/Rebilly/ReDoc/commit/548fae3cbcfc3999cfdb1c8ac582bad30b0afe97

Will be available in the upcoming release

**Comment by RomanGotsiy** [comment] 2019-03-27 20:15
Oh, actually I checked again and I can't reproduce the exact issue you have on the old version.

Could you attach the output of redoc-cli here?

For me it renders as bellow:

![image](https://user-images.githubusercontent.com/3975738/55109141-c8e5ab00-50dd-11e9-9b33-f2b5db311ddb.png)

There is big pacing between sections but smaller between heading and text

**Comment by securisec** [comment] 2019-03-28 06:56
@RomanGotsiy my output is this:
```bash
./node_modules/redoc-cli/index.js bundle ./api/swagger/swagger.yaml --output ./static/docs.html --options.hideDownloadButton

Prerendering docs

🎉 bundled successfully in: ./static/docs.html (1060 KiB) [⏱ 0.381s]
```
I am trying to make it look like the docker docs which looks like this

![image](https://user-images.githubusercontent.com/22226823/55136530-fc721500-5171-11e9-95e9-9541a7dd0d22.png)

**Comment by RomanGotsiy** [comment] 2019-03-28 07:24
No, I mean attach the resulting html so I can check

**Comment by securisec** [comment] 2019-03-28 07:30
Ah, I think i was being dumb. My browser was not in full screen, and the responsive design i think is squishing and increasing the padding. Making the browser full screen fixes the issue.

**Comment by RomanGotsiy** [comment] 2019-03-28 09:13
Ahh, I see now. I will try to make it consistent.

**Comment by hlascelles** [comment] 2019-09-17 15:38
We're seeing this as well. Here is the whitespace around a header in our docs:

![image](https://user-images.githubusercontent.com/299102/65056731-51485880-d969-11e9-8ba0-8ae30ebe2359.png)

Fixing it involves changing the 40px 0px padding to 0px 0px:

```
    .dluJDj {
      padding: 0 0 !important;
    }

    .hiuczA {
      padding: 0 0 !important;
    }
```

Of course, those autogenerated class names change between versions, so it's a losing battle. 

If you're already looking at fixing the above, that's great :+1:

**Closed** 2019-09-30 10:12 UTC

**Comment by hlascelles** [comment] 2019-11-18 14:22
This has not fixed my issue. Specifically, this is nothing to do with small screens. Perhaps it is a different section. I open a new PR.
