### ISSUE TITLE
Render JsonSchema constraints

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redoc#42] opened 2016-04-26 20:34 UTC
- [x] readOnly
- [x] minLength
- [x] maxLength
- [x] pattern
- [x] minItems
- [x] maxItems
- [x] multipleOf
- [x] defaults
- [x] file payload
- [x] `readOnly` - don't show readOnly fields in request schema
- [x] No need to mark `readOnly` in response

to be continued...

**Comment by RomanGotsiy** [comment] 2016-05-18 19:54
Defaults are supported for primitive types only. Need to add this to the known issues

**Comment by MikeRalphson** [comment] 2016-09-13 09:45
@RomanGotsiy Should `dividedBy` actually be `multipleOf`? I don't recognise it from the Swagger spec or JSON Schema draft 4.

**Comment by RomanGotsiy** [comment] 2016-09-13 10:02
@MikeRalphson yes, you're right. Updated.
Thanks

**Comment by nakedible-p** [comment] 2016-10-12 07:47
I know this is marked as post v1.0, but I'd like to mention that we use "pattern" a lot in our API definitions - almost every field is solely determined by pattern - because it is a very simple way to document what kind of values are accepted. Showing that somehow in the rendered documentation would be important for us.

**Comment by RomanGotsiy** [comment] 2016-10-12 10:08
@nakedible-p, `pattern` should be easy to add. I will try to have it done for the next minor release

**Comment by RomanGotsiy** [comment] 2016-11-01 14:58
@nakedible-p finally get to this.
What do you think of the following representation?
![image](https://cloud.githubusercontent.com/assets/3975738/19894078/4d096e90-a054-11e6-833d-af1dcc5dff9d.png)

Maybe you have better idea?

**Comment by nakedible-p** [comment] 2016-11-01 15:05
I think it is perfect. Slashes are the universal regexp indicator.

**Comment by RomanGotsiy** [comment] 2016-11-01 15:09
Great, hopefully will publish new minor release with this today. Max - tomorrow.

**Comment by RomanGotsiy** [comment] 2016-11-02 11:24
@nakedible-p New version is released.

**Comment by fgabolde** [comment] 2018-02-27 15:40
Hello, any hope for `minItems` and `maxItems` ? There is already support for `minLength` and `maxLength` which are basically the same thing for strings.

**Comment by RomanGotsiy** [comment] 2018-03-05 08:57
@fgabolde do you have any ideas of how this may look in ReDoc? Similar to `minLength` and `maxLength`?

**Comment by fgabolde** [comment] 2018-03-09 17:32
Yeah, probably. Right now a size constraint on a string is represented like this:

* `[ 2 .. 8 ] characters` with both constraints set
* `<= 8 characters`, max only
* `>= 2 characters`, min only

Just replacing "characters" with "items" sounds good to me.

**Comment by fgabolde** [comment] 2018-04-17 16:11
I don't see the `pattern` in strings that are used as array items, e.g.:

```yaml
# definition
HTTPSURL:
  type: string
  format: uri
  pattern: "^https?"
```

```yaml
# this one displays "/^https?/" as expected
Thing:
  type: object
  properties:
    single:
      $ref: '#/HTTPSURL'
```

```yaml
# this one does not
ManyThings:
  type: object
  properties:
    multiple:
      type: array
      items:
        $ref: '#/HTTPSURL'
```

I do see the `<uri>` from the format in both cases, and if I add `minLength` it works too.

This is Redoc 1.21.2.

**Comment by unional** [comment] 2019-01-09 00:00
- [ ] no need to mark `required` in response body

**Comment by handrews** [comment] 2019-02-19 04:10
@RomanGotsiy Thank you for the fantastic documentation tool!

However, I'm confused about `readOnly`.

For a POST-to-create I can understand stripping out `readOnly` fields, although not all POST requests have those semantics so it's a somewhat shaky assumption.

For GET and PUT, the HTTP semantics are that the GET response and PUT request are both representations of the target resource, so you **should** be able to do a GET, modify some fields, and PUT it right back.  As long as you don't change the `readOnly` fields, it should be fine (yes, I realize that OpenAPI doesn't like this, but it's a SHOULD and not a MUST and it's ridiculously burdensome to make clients strip out fields when doing GET-modify-PUT).

Similarly, if I want to make a copy of a resource, I'll do a GET of it, tweak it, and then POST the tweaked version back to the collection.

In order to make this behavior clear, the `readOnly` constraint should be rendered on both requests and responses.  Would you be open to some sort of option for displaying it as a constraint?  I would be happy to write a PR.

**Comment by RomanGotsiy** [comment] 2019-02-26 08:24
@handrews yeah, you're right. That's an incorrect assumption 🙈 

I think we can add configuration options to disable stripping out and mark fields as readOnly/readWrite instead.

I will try to do in once I find some time. But your PR would be much appreciated!

**Comment by handrews** [comment] 2019-03-02 02:14
@RomanGotsiy I'll see if I can put something together in the next week-ish.  I took a look and it looks reasonably straightforward- nice job piping the settings through.

Looks like the request body behavior is set in `components/Parameters/Parameters.tsx`, response body in `components/Responses/ResponseDetails.tsx` and examples for both requests and responses in `services/models/MediaType.ts`.  And associated tests.  Let me know if you can think of any other places offhand.

**Comment by calamarico** [comment] 2019-06-10 20:24
@fgabolde I also have the problem that I can't see the `pattern` in `Array of Strings`. Did you find the problem with that?

**Comment by AlexVarchuk** [comment] 2022-05-16 08:42
All constraints were added and the issue is too old. I close that. If someone wants to report supporting additional JsonSchema constraints, feel free to open a new issue.

**Closed by AlexVarchuk** 2022-05-16 08:42 UTC
Labels: Type: Enhancement
