### ISSUE TITLE
Cannot use a dot (.) in path name

### ISSUE THREAD

**Issue by o8e** [Redocly/redoc#1437] opened 2020-10-27 12:30 UTC
Our API is versioned with semantic versioning, i.e 1.0.0.

However we cannot use this in the path as it won't compile.

```
paths:
  '/check/1.0':
```

When we build, we get an error:

`YAMLException: unacceptable kind of an object to dump [object Undefined]`

Also Swagger UI and Editor both fail to compile on dev mode with this.

Is there any way round this?

**Comment by RomanHotsiy** [comment] 2020-10-27 20:37
This looks like a YAML format error. Could you share a bigger chunk of your definition?

**Comment by o8e** [comment] 2020-10-28 10:20
> This looks like a YAML format error. Could you share a bigger chunk of your definition?

```
paths:
  '/check/1.0':
    get:
      summary: Check
      description: Get a vehicle check
      operationId: getCheck
      tags:
        - '1.0'
      security:
        - api_key: []
      parameters:
        - $ref: '#/components/parameters/Vrm'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  check:
                    type: object
                    properties:
                      vrm:
                        type: string
                        example: GN11GYF
[...]
```

There's an extract. If you take 1.0 out of the path, it will work, so it certainly the dot.

**Comment by o8e** [comment] 2020-11-05 10:50
@RomanHotsiy Any luck? This is affecting our ability to provide clients with documentation at the moment 😢

**Comment by adamaltman** [comment] 2020-11-08 22:29
I couldn't reproduce the bug @o8e 

https://github.com/Redocly/openapi-starter/pull/2

**Comment by lornajane** [comment] 2023-07-26 15:53
I can't replicate this either, so I'm closing the issue - please comment if you have more information for us.

**Closed by lornajane** 2023-07-26 15:53 UTC
