### ISSUE TITLE
Splited file schema getting null

### ISSUE THREAD

**Issue by andrecavallari** [Redocly/redoc#1000] opened 2019-08-03 15:49 UTC
I've splited my schemas into files, also the routes, but one of my schemas is outputing wrong in html documentation:
```
{
    "$ref": null
}
```

The files I posted at the gist: https://gist.github.com/andrecavallari/0b85622d7236e6aa5dfa3cb4f1a2587c

Any reference to tag_schema outputs "$ref": null, what I am doing wrong?

The tool schema outputs correctly.

**Comment by andrecavallari** [comment] 2019-08-05 23:05
I was making some tests, and seems that if I use $ref to same file multiple times, it will start outputing that reference as null... Any workaround??
```
{
  "$ref": null
}
```

**Comment by RomanHotsiy** [comment] 2019-08-07 09:15
I don't understand and can't reproduce. The files you posted doesn't allow me to reproduce it.

Share your openapi.yaml

**Comment by merjakaj** [comment] 2019-08-30 11:28
I have encountered similar issue when specifying reusable elements in separate yaml files. If the same "$ref" from another yaml file is referred more than once in the same YAML document, there is compilation error:

Error: Invalid reference token: properties

**Comment by RomanHotsiy** [comment] 2020-01-10 13:33
Closing in favour of #1094

**Closed by RomanHotsiy** 2020-01-10 13:33 UTC
