### ISSUE TITLE
rc51 breaking change

### ISSUE THREAD

**Issue by hotrush** [Redocly/redoc#1573] opened 2021-04-09 10:13 UTC
Just letting you know that rc51 brings breaking changes when using `spec-url`

```
<redoc spec-url='some-url-that-returns-json' hide-download-button="false"></redoc>
```

![image](https://user-images.githubusercontent.com/1247004/114165589-59922b00-9935-11eb-92d9-022ba343cf33.png)

**Comment by eirikur-grid** [comment] 2021-04-09 11:49
Noticed this as well. 
Pinning rc.50 circumvents this issue. The source URL for rc.50 is `https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.50/bundles/redoc.standalone.js`

**Comment by hotrush** [comment] 2021-04-09 11:53
@eirikur-grid yes, switched to rc50, but still - needed to fix this in prod asap 😞 will be glad to see backward compatibility for changes like that

**Comment by RomanHotsiy** [comment] 2021-04-09 13:03
Update:

The issue is caused by the fact your openapi definition endpoint doesn't return the correct mime type for the yaml file and the URL itself doesn't end with `.yml`, `.yaml` or `.json` extension.

We're working on a fix but a temporary workaround would be to either add the `Content-Type` header or add an extension to the url.

**Comment by eirikur-grid** [comment] 2021-04-09 14:28
We are using starlette's OpenAPIResponse.
It has a content type of "application/vnd.oai.openapi" as per https://github.com/OAI/OpenAPI-Specification/issues/110#issuecomment-364498200

**Comment by RomanHotsiy** [comment] 2021-04-09 14:45
Thanks for the details. We'll add support for this mime-type too.

**Comment by RomanHotsiy** [comment] 2021-04-10 12:28
This should be fixed on rc.52. Could anybody confirm, please? Thanks in advance!

**Comment by eirikur-grid** [comment] 2021-04-10 12:58
Confirmed.
<img width="1043" alt="Screenshot 2021-04-10 at 12 58 01" src="https://user-images.githubusercontent.com/50045006/114270527-66c61d00-99fc-11eb-8f04-c50fe51741d7.png">

**Comment by RomanHotsiy** [comment] 2021-04-10 12:59
Great! Thanks!

**Closed by RomanHotsiy** 2021-04-10 12:59 UTC

**Comment by vishnupriyavr** [comment] 2025-04-23 06:23
H@RomanHotsiy  @The same issue is happening with 2.0.0.-rc.75
Commit: d7440fb
This is in conjunction with FastAPI, can you please help with this
