### ISSUE TITLE
Issue with Chrome 77 and angular bootstrapped component.

### ISSUE THREAD

**Issue by pauwlsky** [Redocly/redoc#1050] opened 2019-10-01 20:37 UTC
First off, thank you for all your hard work. We are running into an issue recently we're hoping someone can assist with. 

We are running an angular 8 bootstrapped component alongside redoc 2.0.0-rc.xx (have tried rc.12 through rc.16  and the latest alpha release) and are consistently running into the same issue when trying to render our app documentation. 

basically, we have the following code rendering the bootstrapped component and the docs:

```
<script>
<script src="./path/to/runtime-es2015.js" type="module"></script>
    <script src="./path/to/runtime-es5.js" nomodule></script>
    <script src="./path/to/polyfills-es2015.js" type="module"></script>
    <script src="./path/to/polyfills-es5.js" nomodule></script>
    <script src="./path/to/main-es2015.js" type="module"></script>
    <script src="./path/to/main-es5.js" nomodule></script>
    <script type="text/javascript" src="./path/to/redoc.standalone.js"></script>
</script>

<app-root component="angular-8-bootstrapped-component"></app-root>  <-- our comonent
<redoc spec-url="url/to/swagger.json" hide-download-button></redoc>
```
the docs no longer render and we are getting an error in the console:

```
Uncaught (in promise) TypeError: Method Promise.prototype.then called on incompatible receiver [object Object] at ZoneAwarePromise.then (<anonymous>)
```

This issue started when upgrading to Chrome 77. The issue seems to be arising due to a conflict in the angular 8 scripts and redoc. Removing either the component angular scripts or redoc.standalone.js resolves the issue.

**Comment by wwwater** [comment] 2019-10-02 10:30
We use version: "1.22.2" as a standalone .js and have exactly the same problem in Chrome 77.

**Comment by RomanHotsiy** [comment] 2019-10-02 11:23
Duplicate of https://github.com/Redocly/redoc/issues/1036

**Closed by RomanHotsiy** 2019-10-02 11:23 UTC

**Comment by pauwlsky** [comment] 2019-10-02 18:38
Actually I believe this issue is not the same as #1036. It's not an issue with a `redoc` version.
I think I found a temporary fix for the problem we're running into here:

https://github.com/angular/angular/issues/32802#issuecomment-534606814
