### ISSUE TITLE
Error resolving $ref pointer

### ISSUE THREAD

**Issue by KuSh** [Redocly/redoc#740] opened 2018-12-10 10:38 UTC
I'm using redoc-cli to generate documentation from OpenAPI files. Those files validates and displays correctly in [Swagger Editor](http://editor.swagger.io) but ReDoc has problems with it.

### Actual result

Launching redoc-cli on the problematic file returns the following error:
> SyntaxError: Error resolving $ref pointer "/home/nlecam/#/components/schemas/Link/properties/schema/properties/not/definitions/linkDescription".

Here is a reproduction sample :
```
openapi: 3.0.2
info:
  version: 1.0.0
  title: Reproduction sample
  description: OpenAPI sample that exposes the problem
paths:
  /:
    get:
      description: get
      responses:
        default:
          description: response
          content: {}
components:
  schemas:
    Link:
      $ref: https://json-schema.org/draft-04/hyper-schema#/definitions/linkDescription
```

### Expected result

I expect ReDoc to render the documentation correctly (as Swagger Editor do)

### Notes

Should be linked to or an extension of #541, but I'm using redoc-cli 0.7.0 which include the fix and got the error

regards,
Nicolas

**Comment by RomanGotsiy** [comment] 2018-12-11 13:20
Related issue: https://github.com/APIDevTools/json-schema-ref-parser/issues/112

Thanks for reporting!

**Comment by naomigrace** [comment] 2019-10-18 17:19
I'm getting the same problem. Swagger editor accepts the following:

```

**Comment by KuSh** [comment] 2023-02-13 13:57
I saw that the referenced issue in json-schema-ref-parser was marked fixed but with the slightly updated reproduction case below it still fail with redoc :

```yml
openapi: 3.0.2
info:
  version: 1.0.0
  title: Reproduction sample
  description: OpenAPI sample that exposes the problem
paths:
  /:
    get:
      description: get
      responses:
        default:
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Link"
components:
  schemas:
    Link:
      $ref: https://json-schema.org/draft-04/hyper-schema#/definitions/linkDescription
```

```sh
❯ npx redoc-cli build test.yml
Prerendering docs
Error: Invalid JSON pointer: https://json-schema.org/draft-04/hyper-schema#/definitions/linkDescription
    at Function.parse (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/openapi-sampler/dist/openapi-sampler.js:244:44)
    at Function.get (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/openapi-sampler/dist/openapi-sampler.js:74:60)
    at traverse (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/openapi-sampler/dist/openapi-sampler.js:947:43)
    at traverse (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/openapi-sampler/dist/openapi-sampler.js:953:16)
    at Object.sample (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/openapi-sampler/dist/openapi-sampler.js:426:33)
    at Hn.generateExample (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:73780)
    at new Hn (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:73198)
    at ~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:74232
    at Array.map (<anonymous>)
    at new Gn (~/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:74203)
```

**Comment by jwilmoth-nc** [comment] 2023-06-29 20:19
I can confirm we see this issue as well in ReDoc Version 2.0.0.

**Comment by RomanHotsiy** [comment] 2023-08-09 06:20
The issue is with the https://json-schema.org/draft-04/hyper-schema URL. It doesn't have .json extension neither it returns valid mime-type. So our resolver can't parse this URL.

If I copied the contents of this URL into a gist and replace the link it works as expected:

https://gist.githubusercontent.com/RomanHotsiy/051631cf60825577967b3
a4628468a10/raw/6fe8772590d44baeafaa4feef784d18a2f2bcd4c/test.json#/definitions/
linkDescription

![image](https://github.com/Redocly/redoc/assets/3975738/6ec5e0e8-1d4b-41eb-9cd4-be96154b6cc1)

I'm not sure if we wanna fix it in the bundler.

I'll close this issue now when we know the reason and there is a workaround.

**Closed by RomanHotsiy** 2023-08-09 06:20 UTC

**Comment by RomanHotsiy** [comment] 2023-08-09 06:21
FYI @tatomyr ☝️ 

The corresponding code is here: https://github.com/Redocly/openapi-cli/blob/main/packages/core/src/resolve.ts#L134-L136

Maybe we want to adjust the error message so it includes something: "The URL doesn't respond with a correct Content-Type".

Or we can try to parse json.
